#!/usr/bin/env bash
# Installs Nginx

touch ~/some

sudo apt update -y
sudo apt install nginx -y
sudo service nginx start
echo "Hello World!" | tee /var/www/html/index.html
sudo service nginx restart
